/**
 * 產生存摺浮水印的 glyph 向量路徑（build 期工具，不進 runtime bundle）。
 *
 * 為什麼：sharp（librsvg）在伺服器烘字時找不到 CJK 字型會變成「口口口」豆腐字，
 * 且官方明載「Embedded SVG fonts are not supported」。因此把固定的品牌字樣
 * 預先用 Noto Sans TC 轉成 SVG <path>，runtime 即零字型依賴、跨平台一致。
 *
 * 用法：npm run gen:watermark
 *   需先放好字型檔 assets/fonts/NotoSansTC.ttf（OFL 授權，不入 git）。
 *   產物：src/lib/passbook-watermark-glyphs.ts（已提交，runtime 實際使用）。
 *
 * ⚠ 若更動下方 WATERMARK_TEXT（品牌字樣），務必重跑本腳本重新產生 glyph 檔。
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import opentype from "opentype.js";

const WATERMARK_TEXT = "嘟嘟資訊網 · 嘟嘟資訊網";
const REF_SIZE = 100; // 參考字級；runtime 以 fontSize/REF_SIZE 縮放
const FONT_PATH = resolve(process.cwd(), "assets/fonts/NotoSansTC.ttf");
const OUT_PATH = resolve(process.cwd(), "src/lib/passbook-watermark-glyphs.ts");

function loadFont() {
  let buf: Buffer;
  try {
    buf = readFileSync(FONT_PATH);
  } catch {
    console.error(
      `\n找不到字型檔：${FONT_PATH}\n` +
        "請下載 Noto Sans TC 後放到該路徑（OFL 授權，不需入 git）：\n" +
        "  https://github.com/google/fonts/raw/main/ofl/notosanstc/NotoSansTC%5Bwght%5D.ttf\n",
    );
    process.exit(1);
  }
  // opentype.parse 接受 ArrayBuffer；變體字型會使用預設 master（Regular）外框。
  return opentype.parse(
    buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength),
  );
}

function main() {
  const font = loadFont();
  // baseline 置於 y=0，參考字級 REF_SIZE 取得整串路徑與總前進寬。
  const path = font.getPath(WATERMARK_TEXT, 0, 0, REF_SIZE);
  const d = path.toPathData(2);
  const advance = font.getAdvanceWidth(WATERMARK_TEXT, REF_SIZE);

  const file = `// AUTO-GENERATED by scripts/gen-watermark-glyphs.ts — 請勿手改。
// 若更動品牌字樣，請重跑 \`npm run gen:watermark\`。
export const WATERMARK_TEXT = ${JSON.stringify(WATERMARK_TEXT)};
export const WATERMARK_REF_SIZE = ${REF_SIZE};
export const WATERMARK_ADVANCE = ${Number(advance.toFixed(2))};
export const WATERMARK_GLYPH_PATH =
  ${JSON.stringify(d)};
`;
  writeFileSync(OUT_PATH, file, "utf8");
  console.log(
    `已輸出 ${OUT_PATH}\n  字樣：${WATERMARK_TEXT}\n  寬度(@${REF_SIZE})：${advance.toFixed(2)}\n  路徑長度：${d.length} chars`,
  );
}

main();
